version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tiendung11@
      POSTGRES_DB: smart_api_hub
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=Tiendung11@
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=smart_api_hub
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
